---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: 'yes'
        cache_valid_time: 3600

    - name: CA Certificates
      apt:
        name: ca-certificates

    - name: Install curl
      apt:
        name: curl

    - name: Download JDK
      get_url:
        url: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
        headers: "Cookie:oraclelicense=accept-securebackup-cookie"
        dest: /tmp/jdk-8u201-linux-x64.tar.gz

    - name: Extract JDK tarball
      unarchive:
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: /opt
        creates: /opt/jdk1.8.0_201/
        remote_src: 'yes'
