---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: 'yes'
        cache_valid_time: 3600

    - name: CA Certificates
      apt:
        name: ca-certificates

    - name: Install curl
      apt:
        name: curl

    - name: Download JDK
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
        headers: "Cookie:oraclelicense=accept-securebackup-cookie"
        dest: /tmp/jdk-8u161-linux-x64.tar.gz

    - name: Extract JDK tarball
      unarchive:
        src: /tmp/jdk-8u161-linux-x64.tar.gz
        dest: /opt
        creates: /opt/jdk1.8.0_161/
        remote_src: 'yes'
