pipeline {
    agent any
    environment {
        PATH = "/usr/local/bin:/usr/bin:/opt/apache-maven-3.6.0/bin:/opt/apache-maven-3.6.0/bin:/usr/local/sbin:${env.PATH}"
    }
	        
	 stages {
	    stage("Git Clone"){
		  steps {
		    git 'https://github.com/pavreddy/DevOps-Training.git'
			}
		}	
        stage("Maven Build") {
          steps {
		  
             sh '''
		     mvn -version
			 mvn clean
			 mvn compile
			 mvn test
			 mvn package
		     '''
		  }
		 
		 }
		stage("Archive Artifacts") {
           steps {
             archiveArtifacts 'target/*.war'
           }
		}
	    stage("Tomcat Deploy"){
	      steps {
	        sh 'sudo cp target/DevOps-Training.war /opt/apache-tomcat-8.5.28/webapps/'
	      }
	    }
	    stage("Jboss Deploy"){
	      steps {
	        sh 'sudo cp target/DevOps-Training.war /opt/wildfly/standalone/deployments/'
	      }
	    }	    
	}
}