pipeline {
    agent any
    environment {
        PATH = "/usr/local/bin:/usr/bin:/opt/apache-maven-3.6.0/bin:/opt/apache-maven-3.6.0/bin:/usr/local/sbin:${env.PATH}"
    }
	        
	 stages {
        stage("Maven Build") {
          steps {
		  
             sh '''
		     mvn -version
			 mvn clean
			 mvn compile
			 mvn test
			 mvn package
		     '''
		  }
		 
		 }
	}
}