---
- name: Install Java 1.8 and some basic dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Download JDK
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/7/jdk-7-linux-x64.tar.gz
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com"
    dest: /tmp/jdk-7-linux-x64.tar.gz

- name: Extract JDK tarball
  unarchive:
    src: /tmp/jdk-7-linux-x64.tar.gz
    dest: /opt
    creates: /opt/jdk1.7/
    remote_src: 'yes'

- name: Download JBoss from jboss.org
  get_url:
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  unarchive:
    dest: /usr/share
    src: /opt/jboss-as-7.1.1.Final.zip
    creates: /usr/share/jboss-as
    copy: no

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: /bin/mv jboss-as-7.1.1.Final jboss-as 
  args:
    chdir: /usr/share 
    creates: /usr/share/jboss-as

- name: Copying standalone.xml configuration file
  template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group:
    name: jboss

- name: Add user "jboss"
  user:
    name: jboss
    group: jboss
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  file:
    path: /usr/share/jboss-as/
    owner: jboss
    group: jboss
    state: directory
    recurse: yes

- name: Copy the init script
  copy:
    src: jboss-as-standalone.sh
    dest: /etc/init.d/jboss
    mode: 0755

# - name: Workaround for systemd bug
#   shell: service jboss start && chkconfig jboss on
#   ignore_errors: yes

# - name: Enable JBoss to be started at boot
#   service:
#     name: jboss
#     enabled: yes
#     state: started

- name: "JBoss systemd wrapper for sysvinit script"
  template:
    src: jboss.sysvinit.service.j2
    dest: "/etc/systemd/system/{{ jboss_service }}.service"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0644
  when: ansible_service_mgr == "systemd"

- name: JBoss service
  service:
    name: "{{ jboss_service }}"
    state: started
    enabled: 'yes'