#Jenkins playbook to install and configure the Jenkins server
- hosts: localhost
  vars:
    jenkins_hostname: localhost
  roles:
          #- role: geerlingguy.java
          #become: yes
    - role: ansible-jenkins
      become: yes
    - role: ansible-maven
      become: yes
    - role: ansible-tomcat8
      become: yes    
    - role: ansible-httpd
      become: yes 
    - role: ansible-role-jboss
      become: yes 
    # - role: ansible-jboss
    #   become: yes
