---
- name: Include values per OS Family
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yml"

- name: JBoss OS group
  group:
    name: "{{ jboss_group }}"

- name: JBoss OS user
  user:
    name: "{{ jboss_user }}"
    group: "{{ jboss_group }}"

- name: JBoss home dir
  file:
    path: "{{ jboss_home }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    state: directory
    mode: 0755

- name: Download and Extract Tarball
  unarchive:
    src: "{{ jboss_install_src }}"
    dest: "{{ jboss_home }}"
    extra_opts:
      - "--no-same-owner"
      - "--no-same-permissions"
      - "--strip-components=1"
    creates: "{{ jboss_home }}/jboss-modules.jar"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    remote_src: 'yes'

- name: Management Realm user
  lineinfile:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/mgmt-users.properties"
    line: "{{ jboss_mgmt_user }}={{ [jboss_mgmt_user, 'ManagementRealm', jboss_mgmt_password] | join(':') | hash('md5') }}"
    regexp: "^{{ jboss_mgmt_user }}="
  notify:
    - restart jboss

- name: JBoss properties (binding addresses, ports, etc)
  template:
    src: jboss.properties.j2
    dest: "{{ jboss_home }}/jboss.properties"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0644
  notify:
    - restart jboss

- name: "JBoss {{ jboss_mode }}.conf"
  template:
    src: "{{ jboss_mode }}.conf.j2"
    dest: "{{ jboss_home }}/bin/{{ jboss_mode }}.conf"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0644
  notify:
    - restart jboss

- name: JBoss init configuration file (JAVA_HOME, JBOSS_CONFIG, etc)
  template:
    src: jboss.conf.j2
    dest: "{{ jboss_conf_file }}"
  notify:
    - restart jboss

- name: Update remote secret
  replace:
    path: "{{ jboss_home }}/domain/configuration/host-slave.xml"
    regexp: 'c2xhdmVfdXNlcl9wYXNzd29yZA=='
    replace: '${jboss.domain.slave.password}'
  when: jboss_mode == "domain" and jboss_host_config == "host-slave.xml"

- name: Update remote username
  replace:
    path: "{{ jboss_home }}/domain/configuration/host-slave.xml"
    regexp: '<remote security-realm="ManagementRealm">'
    replace: '<remote security-realm="ManagementRealm" username="${jboss.domain.slave.username}">'
  when: jboss_mode == "domain" and jboss_host_config == "host-slave.xml"

- name: JBoss sysvinit script
  file:
    path: "/etc/init.d/{{ jboss_service }}"
    state: link
    src: "{{ jboss_home }}/docs/contrib/scripts/init.d/wildfly-init-{{ ansible_os_family | lower }}.sh"

- name: "JBoss systemd wrapper for sysvinit script"
  template:
    src: jboss.sysvinit.service.j2
    dest: "/etc/systemd/system/{{ jboss_service }}.service"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: 0644
  when: ansible_service_mgr == "systemd"

- name: JBoss service
  service:
    name: "{{ jboss_service }}"
    state: started
    enabled: 'yes'
